// Writes the Preview-mode sample account for iOS (HealthMateCore resource).
// Seven variants (one per weekday) so weekday-based habits line up after the
// app shifts the dates to "today". Timestamps are floating local times
// ("2026-01-12T08:00:00") that the app reads in the device's time zone.
//   node --experimental-strip-types scripts/export.ts [--check]
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { buildSampleAccount } from "../src/account.ts";

const root = join(dirname(fileURLToPath(import.meta.url)), "..", "..", "..");
const target = join(root, "apps/ios/Packages/HealthMateCore/Sources/HealthMateCore/Resources/sample-account.json");

const variants: Record<string, unknown> = {};
// 2026-01-12 is a Monday; ISO weekdays 1…7.
for (let i = 0; i < 7; i++) {
  const now = new Date(Date.UTC(2026, 0, 12 + i, 12));
  const account = buildSampleAccount(now, "UTC");
  const floating = JSON.parse(JSON.stringify(account), (key, value) =>
    typeof value === "string" && /^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}\.\d{3}Z$/.test(value) ? value.slice(0, 19) : value,
  );
  variants[String(i + 1)] = floating;
}
const json = `${JSON.stringify({ note: "Generated by packages/sample-data/scripts/export.ts. Sample data for Preview mode only. Do not edit.", variants })}\n`;

if (process.argv.includes("--check")) {
  let current = "";
  try {
    current = readFileSync(target, "utf8");
  } catch {}
  if (current !== json) {
    console.error("iOS sample-account.json is out of date. Run: npm run export -w @healthmate/sample-data");
    process.exit(1);
  }
  console.log("iOS sample data is up to date.");
} else {
  writeFileSync(target, json);
  console.log(`wrote ${target} (${(json.length / 1024).toFixed(0)} KB)`);
}
